title: Anthony's Data Project Portfolio
description: Data Science 
description: Exploring Interesting Data Sources and Visualizations
theme: jekyll-theme-hacker
markdown: kramdown

include:
  - style.css

